TILES-4778
2gis/deck2gisLayer pull request #9
Opened 2022-11-16 03:51 UTC by Kuznecoff

Update deck.gl version - up to 8.8.17
Use internal deck types

2022-11-16 09:39 UTC, dnischeta requested changes

2022-11-16 09:39 UTC, ndim3d commented on demo/index.ts
> +    // layer.onAdd();
А почему эти вызовы закомменчены? Может их удалить, если они не нужны совсем.

2022-11-18 08:47 UTC, alxart approved these changes

2022-11-21 07:03 UTC, Kuznecoff commented on demo/index.ts
> +    // layer.onAdd();
точно удалил

2022-11-21 07:25 UTC, dnischeta approved these changes

2022-11-21 08:26 UTC, merged